### PR TITLE
Use elastic-elastic_stack for repo management

### LINKED ISSUE #901: Add elastic_stack::repo
* Module version: Master
* Puppet version: 4.10.x
* OS and version: Ubuntu 16.04

## Bug description
elastic_stack::repo should be used consistently throughout all elastic Puppet modules. 

## Feature Description
- Remove elasticsearch::repo in favor of elastic_stack::repo

I will submit a PR.

### PR DESCRIPTION
**Pull request by baurmatt**
Fixes #901

Pull request acceptance prerequisites:

- [ ] Signed the [CLA](https://www.elastic.co/contributor-agreement/) (if not already signed)
- [ ] Rebased/up-to-date with base branch
- [ ] Tests pass
- [ ] Updated CHANGELOG.md with patch notes (if necessary)
- [ ] Updated CONTRIBUTORS (if attribution is requested)

### CODE REVIEW

**Comment by tylerjl** [comment]
Thanks for taking this on @baurmatt, that's a lot of work and much appreciated!

The CI failures look legitimate, [there's some spots where `repo_version` was still being defined](https://travis-ci.org/elastic/puppet-elasticsearch/jobs/313564402#L1130).

**Comment by baurmatt** [comment]
Sorry, thought after the last commit everything would be fine and went of for the weekend. I've fixed two failures (string2array stuff). I'm not quite sure how to handle the rest. Most of them come from ES 5/6 not supporting site plugins anymore, am I supposed to remove those tests (and elasticsearch::plugin)?

Also: Is there an easy way to only deploy the docker container and investigate what Puppet did? That would drastically ease the fixes which are needed for the PID files path/systemd changes.

**Comment by tylerjl** [comment]
Thanks @baurmatt, I'll keep an eye on the CI failures and figure out which issues are unrelated to your changes.

Regarding iterating faster on tests, you can run the rake rspec tasks prefixed with `BEAKER_destroy=no rake ...` in order to preserve the image after the tests have run in order to hop back into the container and look around.

**Comment by baurmatt** [comment]
Sadly `BEAKER_destroy=no` doesn't help a lot, as elasticsearch gets uninstalled in the last tasks:

```
[root@centos-7-x64 log]# tail -n 1 yum.log
Dec 11 18:02:22 Erased: elasticsearch-5.6.5-1.noarch
```

Is there another way?

**Comment by tylerjl** [comment]
Yeah, stopping Beaker from destroying the image doesn't circumvent the teardown. Some options:

- You can read the log output from a failed test run and re-apply the manifest. Beaker scp's the manifest over and `puppet apply`s it, so you can do the same to recreate the issue. This is a simple way that works reliably for me.
- Alternatively I think you could drop a hard `exit(0)` somewhere in the rspec tests to drop out of the tests before completing them, or inject a `require 'pry' ; binding.pry` to stall the tests while you look.

Admittedly I'm not an rspec expert so these aren't elegant and there may be easier ways. Generally I'd suggest the `BEAKER_destroy=no` method and applying the bad manifest as there hasn't been a case that hasn't worked me using that method yet.

**Comment by jarpy** [comment]
I highly recommend the use of `binding.pry`, for what it's worth. 👍

**Comment by baurmatt** [comment]
Just using `puppet apply` one of the files in /tmp/apply_manifest* works good, thanks! :) Now i'm blocked with the next bug in puppet-elastic-stack -> https://github.com/elastic/puppet-elastic-stack/issues/5

**Comment by baurmatt** [comment]
Ok I think after the last change in puppet-elastic-stack it looks good now. As far as I can tell the errors left are related to changes in ES 5/6 regarding the plugin system and configuration changes for X-Pack/Shield.

**Comment by tylerjl** [comment]
@baurmatt yeah, those are spurious failures after some travis-ci updates. Would you mind terribly merging in master into your branch? I spent yesterday fixing the build so it should be clean now. Merging in master should let us see if there are any lingering problems.

**Comment by baurmatt** [comment]
Done. Lets see what happens :)

**Comment by tylerjl** [comment]
Alright, cool - we've got legitimate failures again. Note that some of the Travis tests don't have enough output so they get killed by Travis so the errors don't get summarized, but see [these tests results for Ubuntu 16.04 as an example where they get through](https://travis-ci.org/elastic/puppet-elasticsearch/jobs/319051749#L733). tl;dr, there are still some acceptance failures where `repo_version` is being used.

**Comment by baurmatt** [comment]
Sorry, i think we have a little misunderstanding here. I aware of the last `repo_version2x` in `spec/acceptance/004_plugin_spec.rb`, it just seems like it doesn't make any difference removing it as ES 5/6 isn't supporting those plugins anymore. That's why i wrote:

>  I'm not quite sure how to handle the rest. Most of them come from ES 5/6 not supporting site plugins anymore, am I supposed to remove those tests (and elasticsearch::plugin)?

Without "fixed" `spec/acceptance/004_plugin_spec.rb`:
```
mbaur@puppet-development:~/Sources/puppet-elasticsearch (feature/elastic_stack_repo) $ rspec spec/acceptance/004_plugin_spec.rb
...
Finished in 4 minutes 14.9 seconds (files took 41.57 seconds to load)
19 examples, 18 failures
...
```

With "fixed" `spec/acceptance/004_plugin_spec.rb`:
```
mbaur@puppet-development:~/Sources/puppet-elasticsearch (feature/elastic_stack_repo *) $ rspec spec/acceptance/004_plugin_spec.rb
...
Finished in 5 minutes 11 seconds (files took 37.51 seconds to load)
19 examples, 18 failures
...
```

Anyway, i just pushed the commit removing the last existence of `repo_version2x` in those tests.

**Comment by tylerjl** [comment]
Technically (unfortunately) this module will still need to support 2.x officially as [it hasn't yet gone end-of-life yet](https://www.elastic.co/support/eol), so we'll need to keep around 2.x tests for a few months still. Keeping them working is kind of a pain but I'll also look into the failures along with you here to try and figure out the best way to update them. I'm working on a branch to ease testing across versions (2.x, 5.x, and 6.x) but it still isn't quite ready yet. 

Some of the failures look like bogus Java version errors; a few days ago I fixed some Java dependency problems on master; if you merge master into your branch those should get fixed. Also as a heads up many of us are heading into holiday vacation so I'll try and keep responsive here but I do apologize if there's a slower turnaround time over the next couple of weeks. 😄

**Comment by baurmatt** [comment]
Thanks! :) I've already have my branch up2date with the current master of puppet-elasticsearch. I'm not quite sure how to support 2.x while using elastic_stack. Should i implement 2.x support into it? I'm also not really sure why this module is supposed to support 2.x until it's official EOL if puppet-logstash isn't. Shouldn't it be enough to keep and old version of this module for people using already/almost EOL versions?

I'm also heading off for vacations until the beginning of January :)

**Comment by tylerjl** [comment]
Thanks, I'll coordinate on the `elastic_stack` side to ensure we're all on the same page. We'll find a way to make a all the pieces work.

**Comment by baurmatt** [comment]
Any update on this? :)

**Comment by tylerjl** [comment]
Cross-referencing here: https://github.com/elastic/puppet-elastic-stack/pull/7

**Pull request merged**
