### PR TITLE
Use absolute class names incase someone creates a different Hash/Arra…

### PR DESCRIPTION
**Pull request by benpillet**
…y class in a different namespace

### CODE REVIEW

**Comment by electrical** [comment]
Hi,

is this something you ran into?
I thought it was fairly isolated?

**Comment by benpillet** [comment]
Yep, I ran into this on my setup because of a legacy code issue where is_a? Hash ends up failing.  I think it's because of one of Datadog's templates at https://github.com/DataDog/puppet-datadog-agent/blob/master/templates/agent-conf.d/nginx.yaml.erb

**Comment by electrical** [comment]
Ahh okay. Never expected this :-)
I'll let Jenkins do its magic and merge it when its green.
Thank you for the contribution!

**Comment by electrical** [comment]
jenkins, test it

**Pull request merged**
