### PR TITLE
Fix dependency related CI breakage

### PR DESCRIPTION
**Pull request by arioch**
This patch fixes unresolved specs errors caused by non-default Gemfile path:

```
+ rake spec
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0)
      puppet-lint (>= 0)
      puppet-syntax (>= 0)
      mocha (>= 0)
      rspec (~> 2.0)
      hiera (~> 1.0)
      json_pure (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/home/bamboo/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:121:in `require': cannot load such file -- rspec-puppet-facts (LoadError)
        from /home/bamboo/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from /home/bamboo/bamboo-home/xml-data/build-dir/2949122/PUP-PUPPETMODULEELASTICSEARCH-JOB1/spec/spec_helper.rb:2:in `<top (required)>'
        from /home/bamboo/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/bamboo/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/bamboo/bamboo-home/xml-data/build-dir/2949122/PUP-PUPPETMODULEELASTICSEARCH-JOB1/spec/classes/000_elasticsearch_init_spec.rb:1:in `<top (required)>'
        from /home/bamboo/.rvm/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1226:in `load'
        from /home/bamboo/.rvm/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
        from /home/bamboo/.rvm/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1224:in `each'
        from /home/bamboo/.rvm/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
        from /home/bamboo/.rvm/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:97:in `setup'
        from /home/bamboo/.rvm/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:85:in `run'
        from /home/bamboo/.rvm/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:70:in `run'
        from /home/bamboo/.rvm/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:38:in `invoke'
        from /home/bamboo/.rvm/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/rspec-core-3.2.1/exe/rspec:4:in `<top (required)>'
        from /home/bamboo/.rvm/gems/ruby-2.1.3/bin/rspec:23:in `load'
        from /home/bamboo/.rvm/gems/ruby-2.1.3/bin/rspec:23:in `<main>'
rake aborted!
/home/bamboo/.rvm/rubies/ruby-2.1.3/bin/ruby -S rspec spec/classes/000_elasticsearch_init_spec.rb spec/classes/001_hiera_spec.rb spec/classes/005_elasticsearch_repo_spec.rb spec/classes/010_elasticsearch_init_unkown_spec.rb spec/classes/099_coverage_spec.rb spec/defines/001_elasticsearch_python_spec.rb spec/defines/002_elasticsearch_ruby_spec.rb spec/defines/003_elasticsearch_template_spec.rb spec/defines/004_elasticsearch_plugin_spec.rb spec/defines/005_elasticsearch_instance_spec.rb spec/defines/010_elasticsearch_service_init_spec.rb spec/defines/011_elasticsearch_service_system_spec.rb --color failed
/home/bamboo/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/home/bamboo/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => spec_standalone
(See full trace by running task with --trace)
```

### CODE REVIEW

**Comment by electrical** [comment]
Hi,

For several reasons i'm currently using separate Gemfiles depending on which task is done.
Before 1.0 comes out i will be consolidating these into a single Gemfile.

**Comment by electrical** [comment]
Hi,

I recently moved out of the separate Gemfiles into a single Gemfile.
Can you confirm this will fix your issue?

**Comment by arioch** [comment]
Not entirely.

It's still failing on git clone parts on my buildserver due to the very common firewall issue that enterprises hardly ever allow Git protocol to pass.

Changing .fixtures.yml from:
```
fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib
    apt: git://github.com/puppetlabs/puppetlabs-apt.git
    zypprepo: https://github.com/deadpoint/puppet-zypprepo.git
  symlinks:
    elasticsearch: "#{source_dir}"
```

to:

```
fixtures:
  repositories:
    stdlib: http://github.com/puppetlabs/puppetlabs-stdlib
    apt: http://github.com/puppetlabs/puppetlabs-apt.git
    zypprepo: https://github.com/deadpoint/puppet-zypprepo.git
  symlinks:
    elasticsearch: "#{source_dir}"
```


and .gemfile:
```
*snip*
gem 'beaker', :git => 'git@github.com:puppetlabs/beaker.git', :branch => 'master'
gem 'beaker-rspec', :git => 'git@github.com:puppetlabs/beaker-rspec.git', :branch => 'master'
gem 'metadata-json-lint', :git => 'https://github.com/nibalizer/metadata-json-lint.git', :branch => 'master'
gem 'rspec-puppet', :git => 'https://github.com/rodjek/rspec-puppet.git', :branch => 'master'
*snip*
```

to:

```
*snip*
gem 'beaker', :git => 'https://github.com:puppetlabs/beaker.git', :branch => 'master'
gem 'beaker-rspec', :git => 'https://github.com:puppetlabs/beaker-rspec.git', :branch => 'master'
gem 'metadata-json-lint', :git => 'https://github.com/nibalizer/metadata-json-lint.git', :branch => 'master'
gem 'rspec-puppet', :git => 'https://github.com/rodjek/rspec-puppet.git', :branch => 'master'
*snip*
```

... would do the trick.

This has the additional benefit of consistency throughout the config files. As it is now it's mixed for no particular reason.

**Comment by electrical** [comment]
Ah, very good point.
Will rectify that today, will not be in a release soon but at least makes development a bit easier.
Thanks!

**Comment by electrical** [comment]
Filed https://github.com/elastic/puppet-elasticsearch/pull/308 to fix this.

**Comment by electrical** [comment]
@arioch should be fixed now. Thank you again for reporting this issue.

**Pull request closed without merging**
