### PR TITLE
Addendum for PR #494, With Tests

### PR DESCRIPTION
**Pull request by x3dfxjunkie**
I hope I'm not stepping on toes, just anxious to get rid of the apt-key warnings with ES! This PR has the items from #494, as well as rpsec tests for both $repo_key_id and $repo_key_source.

### CODE REVIEW

**Comment by electrical** [comment]
jenkins, test it

**Comment by electrical** [comment]
@x3dfxjunkie could you sign our CLA as well please? Thanks!

**Comment by x3dfxjunkie** [comment]
I feel like this was done, twice. :)  Is it not attaching properly to my GitHub ID?

image

**Comment by electrical** [comment]
I'll double check our records and see what went wrong.

**Comment by electrical** [comment]
@x3dfxjunkie the git commit is signed with your @homes.com email address. But can't find it with that email address in our records.

**Comment by x3dfxjunkie** [comment]
Gah, ok.

**Comment by electrical** [comment]
Hehe no worries. I'll check the records in a bit and merge. thank you very much for the patience and contribution!

**Comment by electrical** [comment]
jenkins, test it

**Pull request merged**
