### PR TITLE
Don't remove the init script when using status=>unmanaged

### PR DESCRIPTION
**Pull request by VuokkoVuorinnen**
Fix for issue #499 

Signed-off-by: Patrick Van Brussel <patrick@inuits.eu>

### CODE REVIEW

**Comment by electrical** [comment]
Thanks!
Could you sign the CLA as well? I'll let Jenkins do its magic in the meantime.

**Comment by electrical** [comment]
jenkins, test it

**Comment by VuokkoVuorinnen** [comment]
Signed the CLA in the meantime. Some of the tests will fail, since the service is now present even though the state is unmanaged

**Comment by electrical** [comment]
jenkins, test it

**Comment by electrical** [comment]
There are indeed 2 tests that fail.
Would you be able to modify those so they pass? also make sure that when its unmanaged that we don't enable & start the service.

Thanks!

**Comment by electrical** [comment]
@VuokkoVuorinnen are you able to continue work on this?

**Comment by VuokkoVuorinnen** [comment]
Slipped my mind, reworked the tests now

**Comment by electrical** [comment]
No worries :-) will have Jenkins do its magic.

**Comment by electrical** [comment]
jenkins, test it

**Comment by electrical** [comment]
Hi,

Sorry i completely overlooked this PR and solved it via #554 
Thank you though for the contribution!

**Pull request closed without merging**
