### PR TITLE
Add support for SSL auth on api calls.

### PR DESCRIPTION
**Pull request by dansajner**
Addresses https://github.com/elastic/puppet-elasticsearch/issues/399

### CODE REVIEW

**Comment by dansajner** [comment]
I signed the CLA yesterday.  Not sure why that check is failing.

**Comment by bastelfreak** [comment]
@dansajner did you sign it with a mail address that isn't the one in your github profile or the one you used in the commit?

**Comment by dansajner** [comment]
Looks like my my global git config has a different email address than the one I signed with, but what I signed with matches my github profile.

**Comment by dansajner** [comment]
@bastelfreak do I need to push an update with a different email address?  I pushed a fix to the tests so those should pass if run again.

**Comment by tylerjl** [comment]
Hey @dansajner, sorry for the delayed response here - this looks great, thanks for the PR. The CLA check looks good. :+1:

Sorry for the inconvenience, but I've been updating some of the CI scripts for the repository and it's created a minor conflict so Travis can't test the PR. Could you update your branch with the latest from `master` and push again so it'll get picked up and tested?

From my perspective your changes look good, barring any flags from the test suite.

**Comment by tylerjl** [comment]
The intake tests are showing [a failure when setting a variable to the empty string](https://travis-ci.org/elastic/puppet-elasticsearch/jobs/121195953#L506). I actually wasn't familiar with that check (results of inheriting the project), but after looking at [the check's documentation](https://github.com/voxpupuli/puppet-lint-empty_string-check#variable-assigned-to-the-empty-string) I'm pretty sure this is a valid case for the empty string. According to the [puppet lint docs](http://puppet-lint.com/controlcomments/) we should be able to include something like the following surrounding the assignment to make the linter happy.

    # lint:ignore:empty_string_assignment
    $ssl_args = ''
    # lint:endignore

**Comment by dansajner** [comment]
@tylerjl all tests are passing.

**Pull request merged**
