### PR TITLE
elastic 7.x support (originally from uberjew666)

### PR DESCRIPTION
**Pull request by crazymind1337**
Based on uberjew666's original PR. I have created a branch in my space based on his master and rebased the branch on the current master.

- Update JVM startup options
- Add node name to log4j2.properties
- Rename augeas resource to prevent dependency loop
- Add boolean to enable/disable xpack and required features
- Add self to contributors list
- Add check for required certificate variables
- Add version check for xpack related settings
  Maintains backwards compatibility
- Resolve variable scope warnings
- Update unit tests
- Remove ubuntu 14.04 acceptance tests - Not supported
  https://www.elastic.co/support/matrix

Pull request acceptance prerequisites:

- [x] Signed the [CLA](https://www.elastic.co/contributor-agreement/) (if not already signed)
- [x] Rebased/up-to-date with base branch
- [ ] Tests pass
- [ ] Updated CHANGELOG.md with patch notes (if necessary)
- [ ] Updated CONTRIBUTORS (if attribution is requested)

### CODE REVIEW

**Comment by fatmcgav** [comment]
@crazymind1337 Thanks for taking the time to rebase @uberjew666's PR.

However as mentioned in #1068, this module is currently undergoing a big refactor in order to remove support for running multiple instances on a single node.
So it's highly likely that there will merge conflicts with these changes once that refactoring is completed. 

Some of the changes can certainly be reused though,which I'll aim to do wherever possible.

**Comment by crazymind1337** [comment]
@fatmcgav Thats no problem. I will keep an eye on here. I still need to find a fix for the strange DNS issue in the beaker tests.

**Comment by jacobmw** [comment]
Just wondering if these conflicts can be resolved so that the PR can be merged?

**Comment by crazymind1337** [comment]
> Just wondering if these conflicts can be resolved so that the PR can be merged?

Done.

**Comment by Guillaume001** [comment]
Hello everyone,

Is it possible to include Java 13 and 14 compatible options as it is done in the default jvm.options file of version 7.8.1?
In the same idea, is it possible to update the log4j2.properties file with the missing parameters (audit_rolling) for example.

Thank you in advance

**Comment by grant-veepshosting** [comment]
Hi @crazymind1337 many thanks for this awesome PR.
Do you know if it's still possible to support version 5 clients with this fork?
When I configure "elasticsearch::version: '5.6.16'" on clients already installed working from the Forge released v6.4.0 of the module, after updating some minor config it works just fine EXCEPT the logic in 'spec/spec_utilities.rb' configured the apt repo to try and use:
-deb https://artifacts.elastic.co/packages/5.x/apt stable main
+deb https://artifacts.elastic.co/packages/6.x/apt stable main

Obviously the next upgrade (to a version 6 binary) will break v5 clients.

Any ideas?

**Comment by fatmcgav** [comment]
Elasticsearch 7 support has been released!!!

See https://github.com/elastic/puppet-elasticsearch/issues/1068#issuecomment-750602680

**Pull request closed without merging**
