### PR TITLE
add minimal SLES 12 support

### PR DESCRIPTION
**Pull request by costela**
Unlike #375, this PR does the bare minimum necessary to support SLES12 and therefore uses the same systemd service definition as for other distros. The ```rpmkeys``` problem mentioned in #375 is also a non-issue for SLES 12.

### CODE REVIEW

**Comment by electrical** [comment]
I didn't know SLES 12 supported SystemD? that's a new thing for me.
I'll have to try it out on one of my SLES vagrant boxes.

**Comment by costela** [comment]
Yup, that's one of the biggest changes in SLES 12. Makes supporting it somewhat of a cheat! ;)

**Comment by electrical** [comment]
SLES 11 is still a hell with the weird init scripting, that's something I also still try to support :-(
I'll let Jenkins do its thing for the current functionality and I'll have to find a SLES 12 vagrant box.
If you know of one please let me know :-)

**Comment by electrical** [comment]
jenkins, test it

**Comment by electrical** [comment]
Unit testing failed on the systemd tests because it expected the systemd file to be placed in `/lib/systemd/system/`.
Is there a specific reason to change it for SLES and OpenSuse?

Thanks!

**Comment by costela** [comment]
Yeah, that's where systemd puts them on these distros. My bad for not
updating the unit tests accordingly. Will do it tomorrow, if the change in
itself is acceptable.

**Comment by electrical** [comment]
I must admit i haven't ran the OpenSuse tests for a while, but it always worked on the current location.
I guess there is some kind of symlink in place?

**Comment by costela** [comment]
Not sure why nobody complained on OpenSuse, because I checked today and
/lib/systemd doesn't exist there, so the module shouldn't be working on
OpenSuse either. But maybe I overlooked something obvious?

**Comment by costela** [comment]
Just tested on OpenSuSE 12.1 and there systemd uses /lib/systemd, but 13 uses /usr/lib/systemd. That's probably why nobody noticed the problem on OpenSuSE yet.
Anyway, I've expanded params.pp to account for this.

**Comment by costela** [comment]
jenkins, test it

**Comment by costela** [comment]
jenkins, test it

**Comment by costela** [comment]
oh, overlooked the fact that I can't ask jenkins anything! :/
@electrical, could you do the honors?

**Comment by electrical** [comment]
jenkins, test it

**Comment by electrical** [comment]
@costela still a failure in the unit testing.

http://build-eu-00.elastic.co/job/puppet-elasticsearch-pr-rspec/52/#showFailuresLink

**Comment by costela** [comment]
Oh, sorry, overlooked a local test failure. :/
Should be OK now! Hopefully...

**Comment by electrical** [comment]
No worries :-)
Will wait for Jenkins.

**Comment by electrical** [comment]
jenkins, test it

**Comment by electrical** [comment]
failures related to some stupid gem dependency issue.
Solving that in an other PR, once that is merged i'll trigger this one again.
Sorry for the delay.

**Comment by costela** [comment]
ah, I though those gem failures were a problem with my local setup. Good to know I'm not going crazy! ;)

**Comment by electrical** [comment]
hehe its not you ;-)
fog-core decided to have an open-ended dependency on mime-types.
and due to a bug in bundler not taking the ruby version in account when building up the dependency graph it messes up :-)

**Comment by electrical** [comment]
ruby 2.x tests passed so unit testing is fine. I'll have to do some acceptance tests to ensure it all works.
I'm working on getting a SLES 12 vagrant image so i can run some tests with it.
Thank you for your patience!

**Comment by costela** [comment]
No worries! Thanks for the help!
I just did a minor cosmetic correction in the PR (forgot to change a couple of double-quotes to single-quotes).

**Comment by electrical** [comment]
@costela @buzzdeee Since you both have a PR for SLES but for different versions i want to consolidate that into a single PR so we can support both 11.x and 12.x
Are you guys cool fi someone takes this up or if i do that and you guys can review it ?
This way we can support both versions and make everyone happy in one go.

Thanks!

**Comment by costela** [comment]
@electrical sure thing! I can't commit to doing it myself, but I can definitely review it.

**Comment by buzzdeee** [comment]
@electrical I don't mind either, but similarily, have no real time to merge that, but I'll surely find time for test/review.

**Comment by electrical** [comment]
@costela @buzzdeee thanks for the quick reply guys.
No worries, i'll do the coding for it if you guys can review / test it.
Cheers.

**Comment by tylerjl** [comment]
@costela and @buzzdeee, thanks again for your work here. I've got an upstream PR waiting to be merged at mizzy/specinfra#537 that will give us full test coverage for both SLES 11 and 12. I'm working on merging both your work into a single PR which I'll then open up for review here, so we should get SLES 11, 12, and full acceptance testing for both in one shot (and I'm going to make sure to explicitly merge your commits in git so you're still credited with the work :smile: )

Once it's ready I'll probably close the SLES PRs and open a single one from my fork for both of you to review - let me know if that works for y'all.

Cheers!

**Comment by buzzdeee** [comment]
that's all fine with me.

**Comment by tylerjl** [comment]
Changes have been merged into the combined PR in #609, closing to track in that PR.

**Pull request closed without merging**
