### PR TITLE
Replace elasticsearch_plugin es_version calls with native calls

### PR DESCRIPTION
**Pull request by tylerjl**
Pull request acceptance prerequisites:

- [x] Signed the [CLA](https://www.elastic.co/contributor-agreement/) (if not already signed)
- [x] Rebased/up-to-date with base branch
- [ ] Tests pass
- [x] Updated CHANGELOG.md with patch notes (if necessary)
- [x] Updated CONTRIBUTORS (if attribution is requested)

Historically the call to `elasticsearch -version` has caused lots of problems due to various underlying causes (`JAVA_HOME`, resource constraints, etc.). This change replaces it with code that calls the `package[elasticsearch]` Puppet catalog resource to retrieve the package version instead.

Related to #734

### CODE REVIEW

**Comment by lucabelluccini** [comment]
Does https://github.com/elastic/puppet-elasticsearch/pull/754 make still sense?

**Comment by tylerjl** [comment]
@lucabelluccini it does - although this PR will eliminate the need to call out to ES in `es_version`, all of the commands the provider calls to do things like install/uninstall will still benefit by having `JAVA_HOME` managed in the `with_environment` method (so #754 may need to be updated with this change, but it'll just remove a few lines from the PR).

**Comment by flysen** [comment]
I just stumble on this now. I have a masternode machine with total 16Gb RAM and gave Elastic  `-Xms8g -Xmx8g`. Everything works fine until I do a change and puppet rerun, it runs out of memory.

`Error: /Stage[main]/Main/Node[uuc-logmn012-qa.its.uu.se]/Elasticsearch::Plugin[x-pack]/Elasticsearch_plugin[x-pack]: Could not evaluate: undefined method `scan' for nil:NilClass`

If I log in to the machine and run `/usr/share/elasticsearch/bin/elasticsearch --version`
```
Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000005d4cc0000, 8241020928, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 8241020928 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /root/hs_err_pid3438.log
```
```
free -mh
              total        used        free      shared  buff/cache   available
Mem:            15G        8.8G        4.4G         96M        2.3G        6.1G
Swap:            0B          0B          0B
```
If I add an extra 5Gb RAM it works again and puppet works.
So is there an easy way turning of the "duplicate elasticsearch run" in puppet?

**Comment by tylerjl** [comment]
@flysen thanks for confirming some suspicions about this. The call to `elasticsearch` in the plugin provider to determine the version will go away once this PR makes it into a release. As far as I know, that should be the only place the `elasticsearch` executable is directly called by the provider, so it should solve that specific problem - the provider only calls `bin/plugin` to perform plugin operations so hopefully it doesn't run into memory allocation problem.

**Pull request merged**
