### PR TITLE
allow upgrading plugins

### PR DESCRIPTION
**Pull request by phemmer**
This code enables puppet to handle upgrading plugins. It works by creating a `.name` file in the plugin's directory. If the content of `.name` does not match the name passed to the `elasticsearch::plugin` puppet defined type, puppet wipes the plugin's directory, performs the install, and then creates that `.name` file.

### CODE REVIEW

**Comment by electrical** [comment]
Can you show some code examples on how you would do the upgrade?
its a bit unclear for me from the code.

Thanks!

**Comment by phemmer** [comment]
If you mean puppet code, you might have something like:

```
  elasticsearch::plugin { 'elasticsearch/elasticsearch-cloud-aws/2.1.1':
    module_dir => 'cloud-aws',
  }
```

And to upgrade, you would simply change it to

```
  elasticsearch::plugin { 'elasticsearch/elasticsearch-cloud-aws/2.4.1':
    module_dir => 'cloud-aws',
  }
```

**Comment by electrical** [comment]
Ah i see. let me think about it and see if its testable ( to make sure we don't break it later )

**Comment by drewr** [comment]
LGTM, mutating an install with plugins is a headache.

**Comment by electrical** [comment]
@phemmer I would like to start implementing this PR, are you able to sign the [CLA](https://www.elastic.co/contributor-agreement/) so i can merge it?
Thanks!

I'll take care of any spec / acceptance testing.

**Comment by phemmer** [comment]
CLA signed. Side comment though, requiring lowering browser security settings to do it is a rather unpleasant user experience ([this, step 6](http://i.imgur.com/YJ3TxVB.png))

**Comment by electrical** [comment]
@phemmer thanks for signing it and thank you for the info. I'll pass this on internally.

**Pull request merged**
